### PR TITLE
Added apis and called the needed data

### LINKED ISSUE #6: Assign API objects to variables to be used in JQuery Display
- [x] Actor
- [x] Movies list
- [x] Movie name
- [x] Movie genre
- [x] Movie plot
- [x] Movie availability

### PR DESCRIPTION
**Pull request by magedabdelsalam**

### CODE REVIEW

**Review by MaxHanson07 — CHANGES_REQUESTED** [review]
Need to fix the conflict (step 5 in the thing Denis posted to #resources channel on slack)

**Comment by magedabdelsalam** [comment]
Thank you!! I followed the steps. Should be fine now. Let me know if there's anything else

**Review by magedabdelsalam — COMMENTED** [review]
Followed Denis's steps. Should work now

**Review by magedabdelsalam — COMMENTED** [review]
This should work fine. How do I do a pull request again?

**Review by MaxHanson07 — APPROVED** [review]

**Pull request merged**
